#!/usr/bin/env python3
"""
Script de prueba para el Control de Atajos de Teclado por Gestos
Utiliza MediaPipe Gesture Recognizer para ejecutar atajos de teclado comunes.

Gestos soportados:
1. Victoria (Victory) → Copiar (Ctrl+C)
2. Palma abierta (Open_Palm) → Pegar (Ctrl+V)
3. Puño cerrado (Closed_Fist) → Escape (ESC)
4. Señalar arriba (Pointing_Up) → Actualizar (F5)
5. Pulgar arriba (Thumb_Up) → Deshacer (Ctrl+Z)
6. Pulgar abajo (Thumb_Down) → Rehacer (Ctrl+Y)
7. Te amo (ILoveYou) → Guardar (Ctrl+S)

Controles:
- ESC: Salir del programa
"""

import sys
import os

# Agregar el directorio raíz al path para importar módulos
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from core.controllers.shortcuts_controller import ShortcutsController

def main():
    """Función principal para ejecutar la prueba de control de atajos de teclado."""
    print("="*60)
    print("⌨️ PRUEBA DE ATAJOS DE TECLADO POR GESTOS")
    print("="*60)
    print("🎯 OBJETIVO:")
    print("   Probar la ejecución de atajos de teclado comunes usando")
    print("   7 gestos predefinidos para mayor productividad.")
    print()
    print("🖐️ GESTOS DE CONTROL:")
    print("   ✌️ Victoria (V)          → Copiar (Ctrl+C)")
    print("   ✋ Palma abierta         → Pegar (Ctrl+V)")
    print("   ✊ Puño cerrado          → Escape (ESC)")
    print("   ☝️ Señalar arriba        → Actualizar (F5)")
    print("   👍 Pulgar arriba         → Deshacer (Ctrl+Z)")
    print("   👎 Pulgar abajo          → Rehacer (Ctrl+Y)")
    print("   🤟 Te amo                → Guardar (Ctrl+S)")
    print()
    print("⌨️ FUNCIONES DE ATAJOS:")
    print("   - Copiar: Copia texto o elementos seleccionados")
    print("   - Pegar: Pega contenido del portapapeles")
    print("   - Escape: Cancela operación actual o cierra diálogos")
    print("   - Actualizar: Refresca página web o aplicación")
    print("   - Deshacer: Revierte la última acción realizada")
    print("   - Rehacer: Repite la última acción deshecha")
    print("   - Guardar: Guarda el documento o archivo actual")
    print()
    print("📊 CARACTERÍSTICAS:")
    print("   - Ejecución instantánea de atajos con alta precisión")
    print("   - Umbral de confianza: 70%")
    print("   - Delay entre atajos: 0.8 segundos")
    print("   - Soporte para 1 mano optimizado")
    print("   - Gestos universalmente reconocidos")
    print("   - Estadísticas de uso en tiempo real")
    print("   - Interfaz visual con información detallada")
    print("   - Landmarks de mano dibujados")
    print("   - Indicadores de tiempo de espera")
    print("   - Mensajes de confirmación visual")
    print("   - Threading para ejecución no bloqueante")
    print()
    print("🔧 CONFIGURACIÓN:")
    print("   - Gestos: Victory, Open_Palm, Closed_Fist, Pointing_Up, Thumb_Up, Thumb_Down, ILoveYou")
    print("   - Detección automática sin configuración manual")
    print("   - Delay específico para evitar ejecuciones múltiples")
    print("   - Integración completa con sistema operativo")
    print("   - Manejo robusto de errores")
    print("   - Atajos universales multiplataforma")
    print()
    print("⌨️  CONTROLES:")
    print("   ESC      : Salir del programa")
    print()
    print("🎯 ATAJOS DE TECLADO:")
    print("   📄 COPIAR (Ctrl+C): Copia texto o elementos seleccionados")
    print("   📋 PEGAR (Ctrl+V): Pega contenido del portapapeles")
    print("   ❌ ESCAPE (ESC): Cancela operación o cierra diálogos")
    print("   🔄 ACTUALIZAR (F5): Refresca página web o aplicación")
    print("   ↶ DESHACER (Ctrl+Z): Revierte la última acción")
    print("   ↷ REHACER (Ctrl+Y): Repite acción deshecha")
    print("   💾 GUARDAR (Ctrl+S): Guarda documento actual")
    print()
    print("🔍 REQUISITOS:")
    print("   - Cámara web funcional")
    print("   - Modelo gesture_recognizer.task en models/")
    print("   - pyautogui instalado para ejecución de atajos")
    print("   - Editor de texto o aplicación para probar atajos")
    print("   - Algunos archivos de texto para probar")
    print()
    print("💡 RECOMENDACIONES DE PRUEBA:")
    print("   1. Abre un editor de texto (Notepad, Word, VS Code)")
    print("   2. Escribe algo de texto para probar Copiar/Pegar")
    print("   3. Selecciona texto y usa Victoria (V) para copiar")
    print("   4. Cambia posición del cursor y usa Palma abierta para pegar")
    print("   5. Usa Pulgar arriba para deshacer cambios")
    print("   6. Usa Pulgar abajo para rehacer")
    print("   7. Usa Te amo para guardar documento")
    print("   8. Abre un navegador web y usa Señalar arriba para actualizar")
    print("   9. Usa Puño cerrado para cerrar diálogos")
    print()
    print("🎯 CASOS DE USO:")
    print("   - Edición de documentos sin teclado")
    print("   - Presentaciones interactivas")
    print("   - Control remoto de aplicaciones")
    print("   - Accesibilidad para usuarios con limitaciones")
    print("   - Flujos de trabajo eficientes")
    print("   - Automatización de tareas repetitivas")
    print("   - Control de aplicaciones a distancia")
    print()
    print("⚠️  ADVERTENCIAS:")
    print("   - Los atajos se ejecutarán en la aplicación activa")
    print("   - Asegúrate de tener contenido para copiar/pegar")
    print("   - Ctrl+S guardará en la aplicación actual")
    print("   - Delay de 0.8 segundos entre atajos")
    print("   - F5 actualizará la página/aplicación activa")
    print("   - ESC puede cerrar diálogos o cancelar operaciones")
    print("   - Prueba en aplicaciones seguras primero")
    print()
    print("🔧 ATAJOS IMPLEMENTADOS:")
    print("   - Ctrl+C: Atajo universal para copiar")
    print("   - Ctrl+V: Atajo universal para pegar")
    print("   - ESC: Tecla de escape universal")
    print("   - F5: Atajo universal para actualizar")
    print("   - Ctrl+Z: Atajo universal para deshacer")
    print("   - Ctrl+Y: Atajo universal para rehacer")
    print("   - Ctrl+S: Atajo universal para guardar")
    print()
    print("📱 APLICACIONES SUGERIDAS PARA PRUEBA:")
    print("   - Notepad/TextEdit: Para probar copiar/pegar/guardar")
    print("   - Navegador web: Para probar actualizar")
    print("   - Word/LibreOffice: Para probar edición avanzada")
    print("   - Visual Studio Code: Para programación")
    print("   - Paint/GIMP: Para edición de imágenes")
    print("   - Excel/Calc: Para hojas de cálculo")
    print()
    print("🎨 GESTIÓN DE GESTOS:")
    print("   - Victoria: Dedos índice y medio extendidos en V")
    print("   - Palma abierta: Todos los dedos extendidos")
    print("   - Puño cerrado: Todos los dedos cerrados")
    print("   - Señalar arriba: Solo dedo índice extendido hacia arriba")
    print("   - Pulgar arriba: Solo pulgar extendido hacia arriba")
    print("   - Pulgar abajo: Solo pulgar extendido hacia abajo")
    print("   - Te amo: Pulgar, índice y meñique extendidos")
    print()
    
    try:
        input("Presiona ENTER para comenzar la prueba...")
    except KeyboardInterrupt:
        print("\n❌ Operación cancelada por el usuario")
        return
    
    # Crear y ejecutar el controlador
    try:
        print("\n⌨️ Inicializando controlador de atajos de teclado...")
        controller = ShortcutsController()
        controller.run()
    except Exception as e:
        print(f"❌ Error al ejecutar el controlador: {e}")
        print("   Verifica que:")
        print("   1. La cámara esté disponible")
        print("   2. El modelo gesture_recognizer.task exista en models/")
        print("   3. Las dependencias estén instaladas correctamente:")
        print("      pip install mediapipe opencv-python pyautogui")
        print("   4. pyautogui esté configurado correctamente")
        print("   5. Tengas permisos para ejecutar atajos de teclado")
        print("   6. La aplicación de destino esté activa")
    
    print("\n👋 ¡Gracias por probar los atajos de teclado por gestos!")
    print("   Recuerda: Los gestos naturales hacen el trabajo más eficiente")

if __name__ == "__main__":
    main() 